# ---------------------
# General Configuration
# ---------------------
#How often should events occur (int)
#Time in seconds
eventIntervalLowerBound: 300
eventIntervalUpperBound: 600
#Enable/disable debug mode. Enabling this will produce more log output (boolean)
debugMode: false
#What language should be used (string)
#Note: If the file does not exist in {plugin folder}/MultiplayerEvents/languages/{language}.yml, MultiplayerEvents defaults to 'en.yml'
language: "en"

# ------------
# EventMobKill
# ------------
#Should this event be enabled (boolean)
eventMobKillEnabled: true
#Should any mobs be excluded from this event (string list)
eventMobKillBlacklist:
- ender_dragon
- wither
- wandering_trader
- skeleton_horse
- elder_guardian
#Should we only use hostile mobs for this event (boolean)
eventMobKillHostileOnly: false
#How many mobs should be killed (int)
eventMobKillCountLowerBound: 5
eventMobKillCountUpperBound: 10
#How long should this event last, in seconds (int)
eventMobKillCountDurationLowerBound: 300
eventMobKillCountDurationUpperBound: 900
#How many points should the player get, inclusive (int)
eventMobKillCountRewardLowerBound: 5
eventMobKillCountRewardUpperBound: 20
#Modifier applied per mob that a player didn't kill (float)
#E.g when they need to kill 10 mobs, but they only killed 5, this multiplier is applied to itself 5 times and then to the final amount of points
#E.g: Multiplier = 0.9, with the example above would give (0.9)^5 multiplied by the amount of points they can get
eventMobKillCountRewardMultiplier: 0.9

# -------------------
# EventMoveToLocation
# -------------------
#Should this event be enabled (boolean)
eventMoveToLocationEnabled: true
#Should mobs be spawned to make it trickier for the player (boolean)
eventMoveToLocationEnableMobs: true
#What mobs should be spawned, if enabled (string list)
#Do not include the minecraft: prefix. Lower case only!
eventMoveToLocationMobWhitelist:
- "zombie"
- "skeleton"
- "spider"
- "pillager"
#How far away can the finish be, upper and lower bounds in blocks (int)
eventMoveToLocationDistanceLowerBound: 400
eventMoveToLocationDistanceUpperBound: 1000
#How big is the finish circle radius (int)
eventMoveToLocationFinishRadius: 10
#Should we should particles around the finish (boolean)
eventMoveToLocationFinishShowParticles: true
#How long should this event last, in seconds (int)
eventMoveToLocationDurationLowerBound: 300
eventMoveToLocationDurationUpperBound: 900
#How many points should the winner get, inclusive (int)
eventMoveToLocationRewardLowerBound: 1
eventMoveToLocationRewardUpperBound: 5
#Multiplier for second and third place (float)
eventMoveToLocationRewardSecondMultiplier: 0.7
eventMoveToLocationRewardThirdMultiplier: 0.5
#Multiplier for those that did not make the podium (float)
eventMoveToLocatioNoPodiumModifier: 0.3


# -------------------
# EventItemCommission
# -------------------
# Is the event enabled (boolean)
eventItemCommissionCollectionEnabled: true
# The WorldName of the world where the Chest where the collection point is (string) 
eventItemCommissionCollectionChestWorldName: "world"
# The X, Y and Z coordinates of the Chest where the collection point is (int)
eventItemCommissionCollectionChestX: 0 
eventItemCommissionCollectionChestY: 70
eventItemCommissionCollectionChestZ: 0
# How many different items should be required to complete this event (int)
eventItemCommissionItemCountLowerBound: 1
eventItemCommissionItemCountUpperBound: 10
# What items are not allowed to be used for the commission (string list)
eventItemCommissionItemWhitelist:
- "apple"
- "bread"
- "porkchop"
- "beef"
- "melon_slice"
- "chicken"
- "carrot"
- "rotten_flesh"
- "spider_eye"
- "potato"
- "rabbit"
- "sweet_berries"
- "beetroot"
- "mutton"
- "poppy"
- "dandelion"
- "kelp"
- "sugar_cane"
- "bamboo"
- "cactus"
- "lily_pad"
- "vine"
- "rose_bush"
- "sunflower"
- "tnt"
- "redstone_block"
- "coal"
- "charcoal"
- "iron_ingot"
- "gold_inot"
- "gunpowder"
- "wheat"
- "slime_ball"
- "ender_pearl"
- "honeycomb"
- "ice"
- "cobblestone"
- "oak_log"
- "glass"
- "book"
- "pumpkin"
# How long should this event last, in seconds (int)
eventItemCommissionDurationLowerBound: 1800
eventItemCommissionDurationUpperBound: 3600
#How many points should the winner get, inclusive (int)
eventItemCommissionRewardLowerBound: 20
eventItemCommissionRewardUpperBound: 50