#How often should events occur
#Time in seconds
eventIntervalLowerBound: 300
eventIntervalUpperBound: 600

#EventMobKill
eventMobKillEnabled: true
eventMobKillExclude:
- ender_dragon
- wither
- wandering_trader
- skeleton_horse
- elder_guardian
eventMobKillHostileOnly: false
eventMobKillCountLowerBound: 5
eventMobKillCountUpperBound: 10

#EventMoveToLocation
eventMoveToLocationEnabled: true
eventMoveToLocationEnableMobs: true
eventMoveToLocationDistanceLowerBound: 400
eventMoveToLocationDistanceUpperBound: 1000
eventMoveToLocationFinishRadius: 10
eventMoveToLocationFinishShowParticles: true
eventMoveToLocationDurationLowerBound: 300
eventMoveToLocationDurationUpperBound: 900