#How often should events occur
eventIntervalLowerBound: 300
eventIntervalUpperBound: 600

#EventMobKill
eventMobKillEnabled: true
eventMobKillExclude:
- ender_dragon
- wither
- wandering_trader
- skeleton_horse
- elder_guardian
eventMobKillHostileOnly: false
eventMobKillCountLowerBound: 5
eventMobKillCountUpperBound: 20

#